apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: devops-ide-examples
build:
  artifacts:
    - image: registry/myapp
      context: Docker
      docker:
        dockerfile: Dockerfile
manifests:
  rawYaml:
    - kubernetes/deployment.yaml
    - kubernetes/istio/virtualservice.yaml
    - kubernetes/secret/secret.yaml
