stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - go build -o app
  artifacts:
    paths:
      - app

test:
  stage: test
  script:
    - go test ./...

deploy:
  stage: deploy
  environment: production
  script:
    - ./deploy.sh